### ISSUE TITLE
Use a tick instead of an ‘x’

### ISSUE THREAD

**Issue by csswizardry** [jordanmoore/tinytype#1]
Dunno if it’s just me, but I found a green (presumably meaning ‘yes’) background with an <i>x</i> (which usually means ‘no’) quite confusing.

Perhaps a tick or even the word ‘yes’ might be more appropriate…?

**Comment by jordanmoore** [comment]
Good call Harry, the ticks work much better.

**Comment by csswizardry** [comment]
Nice :D
